//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace curs_reborn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int history_id { get; set; }
        public int group_id { get; set; }
        public int student_id { get; set; }
        public string academ_year { get; set; }
        public System.DateTime hire_date { get; set; }
        public Nullable<System.DateTime> fire_date { get; set; }
    
        public virtual group group { get; set; }
        public virtual student student { get; set; }
    }
}
