//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace curs_reborn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mark
    {
        public int student_id { get; set; }
        public int subject_id { get; set; }
        public int term { get; set; }
        public int mark1 { get; set; }
    
        public virtual subject subject { get; set; }
        public virtual student student { get; set; }
    }
}
